### ISSUE TITLE
Async lib highlighting issues

### ISSUE THREAD

**Issue by antonina-cherednichenko** [sourcegraph/srclib-javascript#37] opened 2016-05-11 17:46 UTC
File https://sourcegraph.com/github.com/caolan/async@master/-/blob/dist/async.js is not highlighted, though it is included in the list of files for analysis and defs/refs are produced.

**Comment by slimsag** [comment] 2016-05-11 18:53
FYI @rothfels confirmed in Slack that we disable syntax highlighting on very large/long files due to the UI perf being slow; so this isn't an issue with srclib-javascript but rather an issue with Sourcegraph itself I think.

**Comment by rothfels** [comment] 2016-05-11 21:39
Yup, closing.

**Closed by rothfels** 2016-05-11 21:39 UTC

**Comment by antonina-cherednichenko** [comment] 2016-05-12 09:59
How can I check that issue is really related to the size of file. Maybe somehow increase file size limit?

How is user informed that file is too big for highlighting?

P.S Inspecting Js console I see the next error - 
_extensions::uncaught_exception_handler:8 Error in event handler for (unknown): SyntaxError: Unexpected token < in JSON at position 0_

**Comment by rothfels** [comment] 2016-05-13 18:04
@antonina-cherednichenko right now, we don't inform the user. Maybe a good idea in development to be able to turn off this behavior; I'll do.
